version: "3.8"

# +----------------------------------------------------------------------------+
# |                                                                            |
# | This file is part of the Qunity package.                                   |
# |                                                                            |
# | Copyright (c) Rodion Kachkin <kyleRQWS@gmail.com>                          |
# |                                                                            |
# | For the full copyright and license information, please view the LICENSE    |
# | file that was distributed with this source code.                           |
# |                                                                            |
# +----------------------------------------------------------------------------+

services:

  # +--------------------------------------------------------------------------+
  # | Nginx                                                                    |
  # +--------------------------------------------------------------------------+
  nginx:
    restart: unless-stopped
    image: ${COMPOSE_PROJECT_NAME}-nginx
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    build:
      context: ./docker/image/nginx
      args:
        - PROJECT_USER=${PROJECT_USER}
    user: ${PROJECT_USER}
    networks:
      - default
    ports:
      - ${PROJECT_PORT}:80
    env_file:
      - ./.env
    working_dir: /usr/share/nginx/html
    volumes:
      - ./project:/usr/share/nginx/html
      - ./docker/socket:/var/socket
      - ./docker/image/nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/image/nginx/etc/server.conf:/etc/nginx/templates/server.conf.template:ro
      - ./docker/image/nginx/etc/fastcgi.conf:/etc/nginx/templates/fastcgi.conf.template:ro

  # +--------------------------------------------------------------------------+
  # | PHP                                                                      |
  # +--------------------------------------------------------------------------+
  php:
    restart: unless-stopped
    image: ${COMPOSE_PROJECT_NAME}-php
    container_name: ${COMPOSE_PROJECT_NAME}-php
    build:
      context: ./docker/image/php
      args:
        - PROJECT_USER=${PROJECT_USER}
    user: ${PROJECT_USER}
    networks:
      - default
    env_file:
      - ./.env
    working_dir: /usr/share/nginx/html
    volumes:
      - ./project:/usr/share/nginx/html
      - ./docker/socket:/var/socket
      - ./docker/image/php/etc/php.conf:/usr/local/etc/php/conf.d/php.ini:ro
      - ./docker/image/php/etc/php-fpm.conf:/usr/local/etc/php-fpm.d/${PROJECT_HOST}.conf:ro
      - ./docker/image/php/etc/opcache.conf:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini:ro
      - ./docker/image/php/etc/xdebug.conf:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}-default
